### PR TITLE
FF8: Add more overridable textures for Worldmap + fixes

### LINKED ISSUE #565: [ FF8 DE NV ] Cannot enter worldmap
**Describe the bug**
The game hang when entering worldmap. Not logs, no crash. The wmx file opening seems the last known step.
This is happening only with DE nvidia patch.

**To Reproduce**
Enter the worldmap with DE nvidia patch.

**Additional notes**
I disabled vram and worldmap modules, and the bug is still there.

### PR DESCRIPTION
**Pull request by myst6re**
## Summary

- Adding ability to override textures from wmset section 39 (rails and roads), 40 and 42 (vehicles).
- Restore ability to mod "texl" textures, even with ff8_worldmap_internal_highres_textures option enabled. + bug fixes
- Add save_textures_legacy to save texture in legacy format instead of recommended one
- Fixes #565
- Texture reload hack mini optimization on worldmap

### ACKs

- [X] I have updated the [Changelog.md](https://github.com/julianxhokaxhiu/FFNx/blob/master/Changelog.md) file
- [X] I did test my code on FF7
- [X] I did test my code on FF8

### CODE REVIEW

File: src/ff8/texture_packer.cpp [hunk 1]
```diff
@@ -42,6 +42,8 @@ void TexturePacker::cleanVramTextureIds(const TextureInfos &texture)
 
 void TexturePacker::cleanTextures(ModdedTextureId previousTextureId, bool keepMods)
 {
+	ffnx_trace("%s: previousTextureId=%d keepMods=%d\n", __func__, previousTextureId, keepMods);
```
Comment (julianxhokaxhiu) [inline src/ff8/texture_packer.cpp:45]: Remember to put an `if` if it's intended to be kept.

Comment (myst6re) [reply src/ff8/texture_packer.cpp:45]: Yes, it is not intended to be kept

File: src/cfg.cpp [hunk 2]
```diff
@@ -342,7 +344,7 @@ void read_cfg()
 		hext_patching_path += "/de";
 		break;
 	case VERSION_FF8_12_DE_NV:
-		hext_patching_path += "/de";
+		hext_patching_path += "/de_nv";
```
Comment (myst6re) [inline src/cfg.cpp:347]: #565

File: src/ff8/vram.cpp [hunk 3]
```diff
@@ -455,7 +521,11 @@ uint32_t ff8_field_read_map_data(char *filename, uint8_t *map_data)
 	snprintf(tex_filename, MAX_PATH, "field/mapdata/%s/%s", get_current_field_name(), get_current_field_name());
 
 	if (save_textures) {
-		ff8_background_save_textures(tiles, mim_texture_buffer, tex_filename);
+		if (save_textures_legacy) {
+			ff8_background_save_textures_legacy(tiles, mim_texture_buffer, tex_filename);
+		} else {
+			ff8_background_save_textures(tiles, mim_texture_buffer, tex_filename);
+		}
```
Comment (julianxhokaxhiu) [inline src/ff8/vram.cpp:528]: You can probably simplify this condition to something like:
```cpp
if (save_textures_legacy)
  ff8_background_save_textures_legacy(tiles, mim_texture_buffer, tex_filename);
else if (save_textures)
  ff8_background_save_textures(tiles, mim_texture_buffer, tex_filename);
```
This way if someone enables the legacy part only it will dump those, if it enables `save_textures` it will dump the FFNx ones. What do you think?

Comment (myst6re) [reply src/ff8/vram.cpp:528]: Maybe it makes sense with more legacy texture names, okay fine I make the change

**Comment by myst6re** [comment]
Ready!

**Review by julianxhokaxhiu — APPROVED** [review]
